#!/bin/bash

partition="$1"

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <partition>" 1>&2
  exit 1
fi

echo "# begin volte hack props"
echo "# autogenerated by $0"
echo "persist.dbg.ims_volte_enable=1"
echo "persist.dbg.volte_avail_ovr=1"
echo "persist.dbg.vt_avail_ovr=1"
echo "persist.dbg.wfc_avail_ovr=1"
echo "persist.data.iwlan.enable=true"
echo "persist.radio.rat_on=combine"
echo "persist.radio.data_ltd_sys_ind=1"
echo "persist.radio.data_con_rprt=1"
echo "persist.radio.calls.on.ims=1"
echo "ro.ril.enable.amr.wideband=1"
echo "# end volte hack props"

echo "# begin common build properties"
echo "# autogenerated by $0"

echo "ro.${partition}.build.date=`$DATE`"
echo "ro.${partition}.build.date.utc=`$DATE +%s`"
echo "ro.${partition}.build.fingerprint=$BUILD_FINGERPRINT"
echo "ro.${partition}.build.id=$BUILD_ID"
echo "ro.${partition}.build.tags=$BUILD_VERSION_TAGS"
echo "ro.${partition}.build.type=$TARGET_BUILD_TYPE"
echo "ro.${partition}.build.version.incremental=$BUILD_NUMBER"
echo "ro.${partition}.build.version.release=$PLATFORM_VERSION"
echo "ro.${partition}.build.version.sdk=$PLATFORM_SDK_VERSION"

echo "ro.product.${partition}.brand=$PRODUCT_BRAND"
echo "ro.product.${partition}.device=$PRODUCT_DEVICE"
echo "ro.product.${partition}.manufacturer=$PRODUCT_MANUFACTURER"
echo "ro.product.${partition}.model=$PRODUCT_MODEL"
echo "ro.product.${partition}.name=$PRODUCT_NAME"

echo "# end common build properties"
